### ISSUE TITLE
Tag problem

### ISSUE THREAD

**Issue by mirasaujan** [alexdrone/Store#12]
Could you please add another number to your next release (like so 1.1.0). SPM is not working otherwise(

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexdrone** [comment]
Done :)

**Comment by regexident** [comment]
Hey, I saw you just released v1.6, thanks for that!

Unfortunately by keeping the `x.y` (vs. the SemVer-compliant `x.y.z`) pattern the package remains unusable from Xcode's SwiftPM integration. 😕

If would of course be nice if Xcode wasn't as strict on the version format, but for the time being doing SemVer the "right way" is the only way to make things work with Xcode.

**Comment by alexdrone** [comment]
Better?

**Comment by regexident** [comment]
Yes, now things work. Thanks! 👍

**Comment by alexdrone** [comment]
Thank you for the help!!
