### ISSUE TITLE
type 'CounterAction' does not conform to protocol 'ActionType'

### ISSUE THREAD

**Issue by mycroftcanner** [alexdrone/Store#13]
`Type 'CounterAction' does not conform to protocol 'ActionType'`

I tried `  typealias AssociatedStoreType = Counter`  and Store<Counter> but it doesn't seem to work. I'll take a nap and try again later.

**Comment by mycroftcanner** [comment]
my mistake...

**Comment by mgcrea** [comment]
@mycroftcanner I'm encountering the same (noob?) mistake, with `Type 'CounterAction' does not conform to protocol 'ActionProtocol'`, `typealias AssociatedStoreType = Counter` does not fix it, any hint?
