### ISSUE TITLE
Is it okay to use a class instead of a struct for a store?

### ISSUE THREAD

**Issue by mycroftcanner** [alexdrone/Store#14]
I am really struggling with this:

```swift
struct RequestLocation: ActionType {
  let location: CLLocation

  func reduce(context: TransactionContext<Store<LocationStore>, Self>) {
    defer {
      // Remember to always call `fulfill` to signal the completion of this operation.
      context.fulfill()
    }
    context.reduceModel { store -> (Void) in
      CoreLocationProxy().locationPublisher().map { location in
        store.location = location
      }
    }
  }
}
```

>>> Compile error: Escaping closure captures 'inout' parameter 'store'

```swift
    context.reduceModel { store -> (Void) in
      store.requestLocationCancellable = store.proxy.locationPublisher().assign(to: \LocationStore.location, on: store)
    }
``` 
>>> Compile error: Cannot convert value of type 'WritableKeyPath<LocationStore, CLLocation>' to expected argument type 'ReferenceWritableKeyPath<_, CLLocation>'

I don't see how to make this work without turning my store into a class. It works then. Would that code any issue?

Some more examples using publishers, etc would be quite useful btw.

**Comment by mycroftcanner** [comment]
```
Fatal error: 'value' must be a struct.: file /Users/az/Library/Developer/Xcode/DerivedData/Felicitas-cswxazuigfewodblckpoedkytppr/SourcePackages/checkouts/Store/Sources/Store/Store.swift, line 11
```

**Comment by mycroftcanner** [comment]
Fatal error: 'value' must be a struct.: ... SourcePackages/checkouts/Store/Sources/Store/Store.swift, line 11

**Comment by mycroftcanner** [comment]
```swift
    context.reduceModel { store -> (Void) in
      store.requestLocationCancellable = store.proxy.locationPublisher()
        .receive(on: RunLoop.main)
        .sink(receiveValue: { location in
          os_log("%d %d", location.coordinate.latitude, location.coordinate.longitude)
        })
    }
```

2019-09-28 11:52:12.184292+0200 Rwork[4975:1328021] 365060354 546416308
2019-09-28 11:52:12.185092+0200 Rwork[4975:1328248] [primary] ▩ (-LprHE5JItuRfMQlwYz8) RequestLocation [2.693875s ms]

this works but I can't figure out a way to mutate my store... Escaping closure captures 'inout' parameter 'store'

**Comment by alexdrone** [comment]
Do you still have issues with this?
