### ISSUE TITLE
Type 'CounterAction' does not conform to protocol 'ActionProtocol'

### ISSUE THREAD

**Issue by mgcrea** [alexdrone/Store#23]
Just copy pasted the TLDR in the README and I'm encountering this error:

```
Type 'CounterAction' does not conform to protocol 'ActionProtocol'
```

Looks similar to #13 but there is no answer there.

I'm a Swift noob so it's probably obvious, looks like it requires a `typealias AssociatedStoreType` property but not sure what I should put there.

Thanks!

---

EDIT, looks like the README is not up to date with the protocol.

**Comment by alexdrone** [comment]
Good find! Could you submit a PR fixing it pretty pls? :D
