### ISSUE TITLE
Handling child stores for lists of data

### ISSUE THREAD

**Issue by zdnk** [alexdrone/Store#26]
I am thinking about using stores for new app I will be working on, but I cannot imagine how would the stores handle showing detail of a movie from the list of movies. 

Imagine if I have app that loads list of items and I select on of the items to see its detail information. I am on the screen, but meanwhile the app updates the list in the background and the corresponding index does not match the same movie now, what will happen, how is this handled/should be handled 

I’ve seen some other examples where there was `selectedItem` in the store/model, but that seems sort of too simple or am I missing something?

**Comment by alexdrone** [comment]
The child store has copy of the subtree that is managing from the parent store, so it will still be able to show the detail page...
