### ISSUE TITLE
[Question] Async action with combine

### ISSUE THREAD

**Issue by nielstj** [alexdrone/Store#27]
Thank you for writing this library, I'm new to this architecture and trying to make it works.
However I'm struggling to implement an async task for reducer.

For example:
 in Counter actions, make a `GET` call to remote server and then increase count with the response.

Can you please show  the proper way to do async / side effect operation?

**Comment by alexdrone** [comment]
Store is based on NSOperation and actions are async by default.

```
struct GetAction: ActionProtocol {
  func reduce(context: TransactionContext<Store<Counter>, Self>) {
    aynchronousFunctionCallWithCallback(...) { result in
      context.reduceModel { $0.count += result }
      context.fulfill()
    }
  }
}
```

Simply call context.fulfill() or reject() whenever your operation is finished.

**Comment by nielstj** [comment]
Understood, so it doesn't support combine publisher right now? Thank you for such swift reply.

**Comment by alexdrone** [comment]
You can absolutely use combine publishers.

```swift
struct FetchPostsAction: ActionProtocol {
  let url: URL
  private var cancellable: AnyCancellable?

  func reduce(context: TransactionContext<Store<Feed>, Self>) {
    cancellable = URLSession.shared.dataTaskPublisher(for: url)
    .map { $0.data }
    .decode(type: [Post].self, decoder: JSONDecoder())
    .replaceError(with: [])
    .eraseToAnyPublisher()
    .sink(receiveValue: { posts in
      context.reduceModel { $0.posts = posts }
    })
  }
  func cancel(context: TransactionContext<Store<Feed>, Self>) {
    cancellable.cancel()
  }
}

```

**Comment by alexdrone** [comment]
PS: I've added a hackernews client as a demo

https://github.com/alexdrone/Store/tree/master/Demo/store_hacker_news

**Comment by nielstj** [comment]
Got it... thank you for the guidance!.
