### ISSUE TITLE
Compilation error in RecorderMiddleware.swift

### ISSUE THREAD

**Issue by majorgilles** [alexdrone/Store#5]
KeyCommands.register(input: "n", modifierFlags: .command) { [weak self] in

=> one of those method calls gives the following error:

type 'KeyCommands' has no member 'register'

**Comment by alexdrone** [comment]
You building with Pods or manually?

**Comment by majorgilles** [comment]
Using Pods

**Comment by alexdrone** [comment]
Ok I've found the issue: pushing a new pod (0.3)

**Comment by alexdrone** [comment]
Published, let me know if everything works fine for you :)

**Comment by majorgilles** [comment]
Yeah no problem, I'll keep updating you if I encounter any issue :)
